IfStatement() 1:1
 BinaryExpression() 1:5
  BinaryExpression() 1:5
   IntegerLiteral(value=1) 1:5
   Token(text==) 1:7
   IntegerLiteral(value=1) 1:9
  Token(text=|) 1:11
  BinaryExpression() 1:13
   IntegerLiteral(value=2) 1:13
   Token(text==) 1:15
   IntegerLiteral(value=2) 1:17
 BlockStatement() 1:20
  ExpressionStatement() 2:5
   CommandCallExpression() 2:5
    Identifier(text="mes") 2:5
    StringLiteral(value="1 = 1 | 2 = 2") 2:9
