IfStatement() 1:1
 BinaryExpression(op="|") 1:5
  BinaryExpression(op="=") 1:5
   IntegerLiteral(value=1) 1:5
   IntegerLiteral(value=1) 1:9
  BinaryExpression(op="&") 1:13
   BinaryExpression(op="=") 1:13
    IntegerLiteral(value=2) 1:13
    IntegerLiteral(value=2) 1:17
   BinaryExpression(op="=") 1:21
    IntegerLiteral(value=3) 1:21
    IntegerLiteral(value=3) 1:25
 BlockStatement() 1:28
  ExpressionStatement() 2:5
   CommandCallExpression() 2:5
    Identifier(text="mes") 2:5
    StringLiteral(value="1 = 1 | 2 = 2 & 3 = 3") 2:9
